version: '3.2'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  runtime:
    build:
      dockerfile: ../Dockerfile.development
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGDATABASE: postgres
    command: /bin/bash -c "while sleep 1000; do :; done"
    volumes:
      - ../:/opt/recollect/app

volumes:
  postgres-data:
